create table if not exists public.data_plans (
  id bigint generated by default as identity primary key,
  network text not null check (network in ('mtn','airtel','glo','9mobile')),
  variation_id text not null,
  gb numeric(10,2) not null default 1,
  active boolean not null default true,
  created_at timestamptz not null default now(),
  unique(network, variation_id)
);

create table if not exists public.data_claims (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  phone text not null,
  network text not null check (network in ('mtn','airtel','glo','9mobile')),
  variation_id text not null,
  status text not null default 'pending' check (status in ('pending','success','failed')),
  provider_reference text,
  provider_response jsonb,
  claim_date date not null default (timezone('utc', now()))::date,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create unique index if not exists data_claims_one_daily_success
on public.data_claims(user_id, claim_date)
where status in ('pending','success');

alter table public.data_plans enable row level security;
alter table public.data_claims enable row level security;

create policy "Users can view active 1GB plans"
on public.data_plans for select to authenticated
using (active = true and gb >= 1);

create policy "Users can view own claims"
on public.data_claims for select to authenticated
using (auth.uid() = user_id);
